### ISSUE TITLE
Webapp seems to be pointing to the wrong OTA file BL602.

### ISSUE THREAD

**Issue by arhi3a** [OpenBekenIOT/webapp#50]
Hello,
While using webapp 
_https://openbekeniot.github.io/webapp/_ on _BL602_ chip.
In the OTA tab there is option to select OTA file to download to PC. After picking version I want to download I get link as below:
_https://github.com/openshwprojects/OpenBK7231T_App/releases/download/1.15.645/OpenBL602_1.15.645.bin_
Flashing with downloaded binary is getting stuck.
I believe that correct hyperlink should lead to OTA version:
_https://github.com/openshwprojects/OpenBK7231T_App/releases/download/1.15.645/OpenBL602_1.15.645_OTA.bin.xz.ota_
which is correct version for OTA binary. Flashing with it succeeded.

**Comment by openshwprojects** [comment]
Thanks for reporting, can you check now?

**Comment by arhi3a** [comment]
Hello, 
Thanks for update, now site directs to correct binary file. (Downloaded file from link & flashed BL602 for test) 
Since it works now I will close the issue.
